[project]
name = "audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.0",
    "scipy>=1.13.1",
    "tensorflow>=2.19.0",
    "torch>=2.7.0",
    "transformers>=4.52.4",
]
